
Vagrant.configure("2") do |config|
  
  #box da usare (sistema operativo)
  #nome vm
  config.vm.box =  "Ubuntu/jammy64"
  config.vm.hostname = "devops.everywhere"

  #impostazioni di rete 
  #assegnazione ip
  config.vm.network "private_network", ip: "192.168.33.40"

  #risorse vm
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Provisioning con uno script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
 
  #scrivi pagina html
   # entra nella cartella 
    # cd /var/www/html
   echo "<!DOCTYPE html>
   <html lang=\"en\">
   <head>
       <meta charset=\"UTF-8\">
       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
       <title>Welcome </title>
   </head>
   <body>
       <h1>devops_everywhere</h1>
       <p>Difficoltà: semplice<br>Creare un progetto Vagrant.<br>Tramite un provisioner a vostra scelta (shell scripting, Puppet, Ansible, Chef, ecc...) configurate una macchina Linux ( nessuna preferenza sulla distribuzione ).
       <br>Sarete liberi di decidere cosa far fare alla macchina. L'importante è che sia portabile.<br>Colui che analizzerà il vostro progetto dovrà eseguire 'vagrant up' e utilizzarla.
       <br>Se non conoscete Vagrant, questo è il momento giusto!!!.
       <br>Il progetto deve veramente essere di base. Date spazio alla fantasia, potete configurare anche una web radio per quanto mi riguarda. L’aspetto fantasioso sarà un dato preferenziale.</p>
   </body>
   </html>" > /var/www/html/index.html

   # Riavvia Apache per applicare le modifiche
   sudo systemctl restart apache2
 SHELL

end
